# Build and test the application

name: "ExchangeCrimeSceneCleaner"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    env:
      DOTNET_VERSION: 6.0.x
      RELEASE_SUBDIR: net6.0

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 #avoid shallow clone so nerdbank gitversioning can do its work, see https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/doc/cloudbuild.md


    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --configuration Release --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat="cobertura" /p:CoverletOutput="TestResults/" /p:UseSourceLink=true

    - name: Publish
      run: dotnet publish src\ExchangeCrimeSceneCleanerCli\ExchangeCrimeSceneCleanerCli.csproj --configuration Release --self-contained true -r win-x64

    - name: Upload build artefact ExchangeCrimeSceneCleanerCli
      uses: actions/upload-artifact@v2
      with:
        name: ExchangeCrimeSceneCleanerCli
        path: D:\a\ExchangeCrimeSceneCleaner\ExchangeCrimeSceneCleaner\src\ExchangeCrimeSceneCleanerCli\bin\Release\${{ env.RELEASE_SUBDIR }}\win-x64\publish

#    - name: Upload build artefact ExchangeCrimeSceneCleanerLibUnitTest
#      uses: actions/upload-artifact@v2
#      with:
#        name: ExchangeCrimeSceneCleanerLibUnitTest
#        path: D:\a\myDupFinder\myDupFinder\tests\rogerbriggen.myDupFinderLibUnitTest\bin\Release\${{ env.RELEASE_SUBDIR }}\

#    - name: Upload build artefact myDupFinderUnitTest TestResults
#      uses: actions/upload-artifact@v2
#      with:
#        name: myDupFinderLibUnitTestCodeCoverage
#        path: D:\a\myDupFinder\myDupFinder\tests\rogerbriggen.myDupFinderLibUnitTest\TestResults\
